#!/bin/sh
queries=$1
shift
filelist=$1
shift

export CLASSPATH=/usr/share/java/lucene2-demos.jar:/usr/share/java/lucene2.jar
java org.apache.lucene.demo.SearchFiles  -queries "$queries" -paging 50000 | sed -n 's/^[0-9]\+\. \(.*\)$/\1/p' | sort | uniq -c | sort -nr > $filelist
